/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.View_penjualan;


import java.sql.SQLException;
import com.Controller.jenis_controller;
import com.Model_penjualan.JenisBarang;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Alifiyah
 */
public class Menu_JenisBarang extends javax.swing.JFrame {

    jenis_controller jc;
    DefaultTableModel mdlJenis = new DefaultTableModel(new String[]{"ID","JENIS BARANG"},0);
    String IdJenis;
    String Namajenis;
    
    public Menu_JenisBarang() throws SQLException{
        initComponents();
        this.setLocationRelativeTo(null);
        this.jc = new jenis_controller();
        tampilDataJenis();
        
        this.table_jenis.addMouseListener(new java.awt.event.MouseAdapter()
        {
             public void mouseClicked(java.awt.event.MouseEvent e)
                {

            int row=table_jenis.rowAtPoint(e.getPoint());
            IdJenis = table_jenis.getValueAt(row,0).toString();
            Namajenis = table_jenis.getValueAt(row, 1).toString();
                
            teks_jenisbarang.setText(Namajenis);
                }
            
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        teks_jenisbarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_jenis = new javax.swing.JTable();
        Insert_jenis = new javax.swing.JButton();
        Update_jenis = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Jenis Barang :");

        table_jenis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_jenis);

        Insert_jenis.setText("Insert");
        Insert_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_jenisActionPerformed(evt);
            }
        });

        Update_jenis.setText("Update");
        Update_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_jenisActionPerformed(evt);
            }
        });

        ButtonBack.setText("Back");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Insert_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Update_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(teks_jenisbarang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(teks_jenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Insert_jenis)
                            .addComponent(Update_jenis))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonBack)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Insert_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_jenisActionPerformed
        // TODO add your handling code here:
        String jenis = teks_jenisbarang.getText();
        
        try {
            jc.InsertJenis(jenis);
            JOptionPane.showMessageDialog(this, "Anda Berhasil Menambah Jenis barang");
            tampilDataJenis();
            teks_jenisbarang.setText("");
        } catch (Exception e) {
            System.err.println("Error:"+e);
        }
    }//GEN-LAST:event_Insert_jenisActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void Update_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_jenisActionPerformed
        Namajenis= teks_jenisbarang.getText();
        try {
            jc.UpdateJenis(IdJenis, Namajenis);
            tampilDataJenis();
            teks_jenisbarang.setText("");
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_Update_jenisActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton Insert_jenis;
    private javax.swing.JButton Update_jenis;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_jenis;
    private javax.swing.JTextField teks_jenisbarang;
    // End of variables declaration//GEN-END:variables

     public void tampilDataJenis()throws SQLException{
       mdlJenis.setRowCount(0);
            for(JenisBarang p : this.jc.getDatajenis()){
                mdlJenis.addRow(new String[]{ p.getId_jenis().toString() , p.getJenis_barang()});
            }
            table_jenis.setModel(mdlJenis);
    }
     
    
}
