/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.View_penjualan;

/**
 *
 * @author Alifiyah
 */
import com.Controller.barang_Controller;
import com.Controller.jenis_controller;
import com.Model_penjualan.Barang;
import com.Model_penjualan.JenisBarang;
import com.sun.jdi.Value;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Menu_Barang extends javax.swing.JFrame {

    barang_Controller bc;
    jenis_controller jc;
    DefaultTableModel mdlBarang = new DefaultTableModel(new String[]{"ID","NAMA BARANG","JENIS BARANG","HARGA","SATUAN"},0);
    String IdBarang;
    String IdJenis;
    String NamaBarang;
    String JenisBarang;
    String Satuan;
    String Harga;
    
    public Menu_Barang() throws SQLException{
        initComponents();
        this.setLocationRelativeTo(null);
        this.bc = new barang_Controller();
        this.jc = new jenis_controller();
        tampilDataBarang();
        ShowComboBoxjenis();
        
        this.table_barang.addMouseListener(new java.awt.event.MouseAdapter()
        {
             public void mouseClicked(java.awt.event.MouseEvent e)
                {

            int row=table_barang.rowAtPoint(e.getPoint());
            IdBarang = table_barang.getValueAt(row,0).toString();
            NamaBarang = table_barang.getValueAt(row,1).toString();
            //JenisBarang = table_barang.getValueAt(row,2).toString();
            Harga = table_barang.getValueAt(row,3).toString();
            Satuan = table_barang.getValueAt(row,4).toString();
            
            teks_namaBarang.setText(NamaBarang);
            teks_harga.setText(Harga);
            teks_satuan.setText(Satuan);
            //combo_jenis.setSelectedItem(jenis_barang);

            }

        });
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nama = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        teks_namaBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        teks_satuan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        teks_harga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_barang = new javax.swing.JTable();
        combo_jenis = new javax.swing.JComboBox<>();
        insert_barang = new javax.swing.JButton();
        Update_barang = new javax.swing.JButton();
        delete_barang = new javax.swing.JButton();
        jenis_barang = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_nama.setText("Nama Barang :");

        jLabel3.setText("Jenis Barang :");

        jLabel4.setText("Satuan :");

        jLabel5.setText("Harga :");

        table_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_barang);

        combo_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        insert_barang.setText("Insert");
        insert_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_barangActionPerformed(evt);
            }
        });

        Update_barang.setText("Update");
        Update_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_barangActionPerformed(evt);
            }
        });

        delete_barang.setText("Delete");
        delete_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_barangActionPerformed(evt);
            }
        });

        jenis_barang.setText("Data Jenis");
        jenis_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_barangActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label_nama)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(combo_jenis, 0, 98, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(teks_namaBarang))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(teks_harga)
                                            .addComponent(teks_satuan)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(insert_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(536, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jenis_barang)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Update_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delete_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Update_barang)
                            .addComponent(delete_barang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jenis_barang)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_nama)
                            .addComponent(teks_namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(combo_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teks_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teks_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insert_barang)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_barangActionPerformed
        // TODO add your handling code here:
        String Nama_barang = teks_namaBarang.getText();
        String Id_jenis = jc.arrjenis.get(combo_jenis.getSelectedIndex()).getId_jenis().toString();
        String Harga = teks_harga.getText();
        String Satuan = teks_satuan.getText();
        
        try {
            bc.InsertBarang( Id_jenis,Nama_barang, Harga, Satuan);
            JOptionPane.showMessageDialog(this,"Anda telah berhasil insert barang");
            tampilDataBarang();
            
            teks_namaBarang.setText("");
            teks_satuan.setText("");
            teks_harga.setText("");
            
        } catch (Exception e) {
            System.err.print("Error :"+e);
        }
        
    }//GEN-LAST:event_insert_barangActionPerformed

    private void jenis_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_barangActionPerformed
       
        try {
            Menu_JenisBarang menujenis = new Menu_JenisBarang();
            menujenis.setVisible(true);
            
           
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Barang.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_jenis_barangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Update_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_barangActionPerformed
        try {
            String IdJenis = jc.arrjenis.get(combo_jenis.getSelectedIndex()).getId_jenis().toString(); 
            NamaBarang= teks_namaBarang.getText();
            Harga= teks_harga.getText();
            Satuan= teks_satuan.getText();
            bc.UpdateBarang(IdBarang,IdJenis, NamaBarang, Harga, Satuan);
            tampilDataBarang();
            
            teks_namaBarang.setText("");
            teks_satuan.setText("");
            teks_harga.setText("");
           
   
        } catch (Exception e) {
            System.err.println(e);
        }
        
       
    }//GEN-LAST:event_Update_barangActionPerformed

    private void delete_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_barangActionPerformed
        try {
            bc.DeleteBarang(IdBarang);
            tampilDataBarang();
            teks_namaBarang.setText("");
            teks_satuan.setText("");
            teks_harga.setText("");
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_delete_barangActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update_barang;
    private javax.swing.JComboBox<String> combo_jenis;
    private javax.swing.JButton delete_barang;
    private javax.swing.JButton insert_barang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jenis_barang;
    private javax.swing.JLabel label_nama;
    private javax.swing.JTable table_barang;
    private javax.swing.JTextField teks_harga;
    private javax.swing.JTextField teks_namaBarang;
    private javax.swing.JTextField teks_satuan;
    // End of variables declaration//GEN-END:variables
    public void tampilDataBarang()throws SQLException{
       mdlBarang.setRowCount(0);
            for(Barang p : this.bc.getDatabarang()){
                mdlBarang.addRow(new String[]{ p.getId_barang().toString() , p.getNama_barang(),p.getjenis(), p.getHarga().toString(), p.getSatuan().toString()  });
            }
            table_barang.setModel(mdlBarang);
    }
    
    public void ShowComboBoxjenis() throws SQLException{
        DefaultComboBoxModel dcbmJenis = new DefaultComboBoxModel();
        for (JenisBarang p : this.jc.getDatajenis()){
            dcbmJenis.addElement(p.getJenis_barang());  
        }
        this.combo_jenis.setModel(dcbmJenis);
    }
   
    }


